In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [19]:
#importing the dataset
dataset = pd.read_excel('production_data.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [20]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [21]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [22]:
#Splliting the data into train set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [23]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [24]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [25]:
print(x_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [26]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [27]:
#Initializing the artificial neural network
ann = tf.keras.models.Sequential()

In [28]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [29]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [30]:
#Adding the output layer 
ann.add(tf.keras.layers.Dense(units=1))

In [31]:
#Compiling the artificial neural network
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [32]:
#Training the artificial neural network model 
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 468us/step - loss: 159238.8281
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - loss: 342.0059
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - loss: 236.3748
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 229.3575
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - loss: 222.3450
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - loss: 212.0999
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - loss: 204.2745
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - loss: 188.3707
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - loss: 177.0214
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - loss: 161.8052
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 149.2962
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - loss: 139.6246
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - loss: 121.2448
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step -

In [33]:
#Predicting the result
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step
[[431.42 431.23]
 [462.59 460.01]
 [466.12 461.14]
 ...
 [473.35 473.26]
 [440.05 438.  ]
 [459.33 463.28]]
