In [236]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [237]:
#importing the dataset
dataset = pd.read_excel('production_data.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [238]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [239]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [240]:
#Splliting the data into train set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [241]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [242]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [243]:
print(x_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [244]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [245]:
#Initializing the artificial neural network
ann = tf.keras.models.Sequential()

In [246]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [247]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [248]:
#Adding the output layer 
ann.add(tf.keras.layers.Dense(units=1))

In [249]:
#Compiling the artificial neural network
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [250]:
#Training the artificial neural network model 
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 466us/step - loss: 119.3022
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - loss: 61.0409
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - loss: 46.1667
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - loss: 37.3747
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - loss: 35.2992
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - loss: 34.6970
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - loss: 33.4588
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - loss: 31.1382
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - loss: 31.7156
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - loss: 30.4848
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - loss: 29.5409
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - loss: 29.5031
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step - loss: 29.1610
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - loss: 28.4426


In [251]:
#Predicting the result
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step
[[430.89 431.23]
 [461.98 460.01]
 [465.54 461.14]
 ...
 [472.74 473.26]
 [439.39 438.  ]
 [458.67 463.28]]
